name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test to run
        required: true
        type: choice
        default: all
        options:
           - all
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: action/checkout@v4
      - name: Set up Python env
        uses: action/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependenciens
        run: pipi install -r requirements.txt
      - name: Run tetss
        run: pytest -v
