name: Run autotests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select test suite to run
        required: true
        type: choice
        default: all
        options:
          - all
          - unit
          - integration  # Add more options as needed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Remove bundled wheel files
        run: find . -type f -name "*.whl" -delete || true

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y build-essential libxml2-dev libxslt-dev python3-dev

      - name: Install lxml from source
        run: pip install --no-binary lxml lxml==5.1.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" == "all" ]; then
            pytest -v
          elif [ "${{ github.event.inputs.deployment_target }}" == "unit" ]; then
            pytest -v tests/unit
          elif [ "${{ github.event.inputs.deployment_target }}" == "integration" ]; then
            pytest -v tests/integration
          fi
